[[redirects]]
  from = "/*"
  to = "/"


[[redirects]]
  from = "/users"
  to = "https://covidslayer-api.herokuapp.com"
  status = 200
  force = true

[[redirects]]
  from = "/games"
  to = "https://covidslayer-api.herokuapp.com"
  status = 200
  force = true
  
